### ISSUE TITLE
Failed to connect to camera service

### ISSUE THREAD

**Issue by pSnehanshu** [tjvantoll/nativescript-flashlight#12]
I am new to NativeScript, please help me.
When I try `flashlight.on()` or `flashlight.toggle()`, the following error happens, why is it happening?
<pre>
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

Error: java.lang.RuntimeException: Fail to connect to camera service
    android.hardware.Camera.<init>(Camera.java:532)
    android.hardware.Camera.open(Camera.java:361)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
    android.view.View.performClick(View.java:5205)
    android.view.View$PerformClick.run(View.java:21164)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight.js, line: 14, column: 35

StackTrace: 
	Frame: function:'flashlight.on', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight.js', line: 14, column: 36
	Frame: function:'toggle', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight-common.js', line: 8, column: 15
	Frame: function:'flash', file:'file:///data/data/org.nativescript.Browse/files/app/page2.js', line: 12, column: 20
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
	Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
	at android.view.View.performClick(View.java:5205)
	at android.view.View$PerformClick.run(View.java:21164)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Fail to connect to camera service
	at android.hardware.Camera.<init>(Camera.java:532)
	at android.hardware.Camera.open(Camera.java:361)
	... 16 more
</pre>

**Comment by corebreaker** [comment]
Authorize Camera permission on the application.

**Comment by corebreaker** [comment]
Ok, nevermind; i had the same error (_**Fail to connect to camera service**_) few hours ago and it has resolved by permissions.

Good luck.

**Comment by pSnehanshu** [comment]
Okay, I was able to fix the first error, now after taking permissions, there are more error due to [this line](https://github.com/tjvantoll/nativescript-flashlight/blob/e7c378f061935b5f216b4093e3a9db34163d6a29/flashlight.android.js#L17).
<pre>
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

TypeError: Cannot read property 'FLASH_MODE_TORCH' of undefined
File: "file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight.js, line: 17, column: 42

StackTrace: 
	Frame: function:'flashlight.on', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight.js', line: 17, column: 43
	Frame: function:'toggle', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-flashlight/flashlight-common.js', line: 8, column: 15
	Frame: function:'flash', file:'file:///data/data/org.nativescript.Browse/files/app/page2.js', line: 13, column: 24
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
	Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
	at android.view.View.performClick(View.java:5205)
	at android.view.View$PerformClick.run(View.java:21164)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
</pre>

**Comment by pSnehanshu** [comment]
Basically this is my code
<pre>
const permissions = require( "nativescript-permissions" );
const flashlight = require("nativescript-flashlight");

function flash(){
    if (flashlight.isAvailable()){

        if( permissions.hasPermission(android.Manifest.permission.CAMERA) ){
            flashlight.toggle();
        }
        else{
            permissions.requestPermission(android.Manifest.permission.CAMERA, "I need these permissions because I'm cool")
                .then(function() {
                    flashlight.toggle();
                })
                .catch(function() {
                    alert("Unable to seek permission.");
                });
        }
    }
    else{
        alert("There's no Camera in your phone.");
    }
}

</pre>

**Comment by corebreaker** [comment]
Yes, master branch is not up to date, this notified by issue #14 , and it will be resolved with PR #10 or #13

**Comment by corebreaker** [comment]
If you want resolve it now, do uninstall this plugin (`tns plugin remove nataivesctipt-flashlight`), and install the EddyVerbruggen's forked version of this plugin by:
```shell
tns plugin add git+https://github.com/EddyVerbruggen/nativescript-flashlight.git
```

**Comment by mbariola** [comment]
I had the same problem, in which the device console reports that app failed to get camera permissions.
I am using Eddie Verbruggen's version (actually I tried them all).

It seems that at least on my android oreo (Oneplus 3T) FLASHLIGHT is no good as a permission and I need to request CAMERA. It makes no sense to me since I only want the flashlight and cannot pin it on something changing in Android versions or something with the plugin.

Either way, requesting CAMERA instead of FLASHLIGHT fixed the "Can't get permissions" problem. Not happy with not understanding why, but it'll need to do atm.
