### ISSUE TITLE
 Calling js method onClick failed

### ISSUE THREAD

**Issue by jaffarhussain1011** [tjvantoll/nativescript-flashlight#9]
I have created new project using
`tns create jkflashlight`
then adjust main-page.xml
main-page.js
after this run 
`tns run android`
checked in genimotion it was wokring fine because i was able to see alert that flash light support is not available.
then i created key using keytool
then i created apk using key generated above.
build was successful.

then i loaded apk in android device and clicked on "Turn on" button
and app crashed.
following is stacktrace.
`FATAL EXCEPTION: main
                                                   Process: org.nativescript.jkflashlight, PID: 30698
                                                   com.tns.NativeScriptException: 
                                                   Calling js method onClick failed
                                                   
                                                   TypeError: Cannot read property 'FLASH_MODE_TORCH' of undefined
                                                   File: "/data/data/org.nativescript.jkflashlight/files/app/tns_modules/nativescript-flashlight/flashlight.js, line: 16, column: 42
                                                   
                                                   StackTrace: 
                                                   	Frame: function:'flashlight.on', file:'/data/data/org.nativescript.jkflashlight/files/app/tns_modules/nativescript-flashlight/flashlight.js', line: 16, column: 43
                                                   	Frame: function:'flashlight.toggle', file:'/data/data/org.nativescript.jkflashlight/files/app/tns_modules/nativescript-flashlight/flashlight-common.js', line: 7, column: 15
                                                   	Frame: function:'viewModel.toggleFlashlight', file:'/data/data/org.nativescript.jkflashlight/files/app/main-page.js', line: 21, column: 20
                                                   	Frame: function:'Observable.notify', file:'/data/data/org.nativescript.jkflashlight/files/app/tns_modules/data/observable/observable.js', line: 146, column: 32
                                                   	Frame: function:'Observable._emit', file:'/data/data/org.nativescript.jkflashlight/files/app/tns_modules/data/observable/observable.js', line: 168, column: 18
                                                   	Frame: function:'_android.setOnClickListener.android.view.View.OnClickListener.onClick', file:'/data/data/org.nativescript.jkflashlight/files/app/tns_modules/ui/button/button.js', line: 33, column: 32
                                                   
                                                   
                                                       at com.tns.Runtime.callJSMethodNative(Native Method)
                                                       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
                                                       at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
                                                       at com.tns.Runtime.callJSMethod(Runtime.java:716)
                                                       at com.tns.Runtime.callJSMethod(Runtime.java:697)
                                                       at com.tns.Runtime.callJSMethod(Runtime.java:687)
                                                       at com.tns.gen.android.view.View_OnClickListener.onClick(android.view.View$OnClickListener.java)
                                                       at android.view.View.performClick(View.java:4764)
                                                       at android.view.View$PerformClick.run(View.java:19844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)`

please help me in this regard.

**Comment by losbeekos** [comment]
I've got the same problem on my LG G3 with android 6.0.

`camera.Parameters`
is undefined so it can't set the the flash property.

`camera`
seems to work and returns 'android.hardware.Camera@9f3408f' in my case.

**Comment by romgom** [comment]
try this in your _flashlight.android.js_  .. tested only in android device.. (grand duos to be specific)

change "**camera**" to "**android.hardware.Camera**" in both _**setFlashMode**_
_ON_:   parameters.setFlashMode(**_android.hardware.Camera_**.Parameters.FLASH_MODE_TORCH);
_OFF_:   parameters.setFlashMode(**_android.hardware.Camera_**.Parameters.FLASH_MODE_OFF);

add **camera = null;** after release() :)

**Comment by corebreaker** [comment]
Same problem.
